version: '3.7'

services:
  money-tracker:
    image: node:18-bullseye
    container_name: money-tracker
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
